# Generated by Django 3.2.9 on 2021-11-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(null=True, related_name='category', to='goodsapp.Category', verbose_name='Категории'),
        ),
    ]
