# Generated by Django 3.2.9 on 2021-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20211130_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(related_name='category', to='goodsapp.Category', verbose_name='Категории'),
        ),
    ]
