# Generated by Django 3.2.9 on 2021-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('goodsapp', '0004_auto_20211202_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='site',
            field=models.ManyToManyField(related_name='sites', to='sites.Site'),
        ),
    ]
